-- Migration: Create Brand and Model tables
-- This migration creates the Brand and Model tables for the e-commerce platform

CREATE TABLE IF NOT EXISTS public."Brand" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null,
  image_url text null,
  constraint Brand_pkey primary key (id),
  constraint Brand_name_key unique (name)
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.model (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  year integer null,
  name text null,
  specs text null,
  constraint model_pkey primary key (id),
  constraint model_name_key unique (name)
) TABLESPACE pg_default;

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_brand_name ON public."Brand" USING btree (name) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_model_name ON public.model USING btree (name) TABLESPACE pg_default;
